config/routes.rb
Rails.application.routes.draw do
  get 'items/new'

  devise_for :users
  resources :users, only: [:show] do
    resources :items, only: [:new, :create, :destroy]
  end
  
  get 'welcome/home'
  get 'welcome/about'

  authenticated :user do
    root to: "users#show", :as => "profile", :as => "item"
  end
  root to: 'welcome#home'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  
  def days_left
    (DateTime.now.to_date - created_at.to_date).to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_many :items, :dependent => :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
    @user = current_user
  end
  
  def create
    @item = current_user.items.new(params.require(:item).permit(:name))
    if @item.save
      redirect_to '/', notice: "Item was saved successfully."
    else
      flash[:error] = "Error creating item. Please try again."
      render :new
    end
  end
  
  def destroy
    @item = current_user.items.find(params[:id])
 
    if @item.destroy
      flash[:notice] = "To-Do Item was deleted."
    else
      flash[:error] = "To-Do Item couldn't be deleted. Try again."
    end
    
    respond_to do |format|
      format.html
      format.js
    end
    
  end
  
  private

  def comment_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
    if @user
      @items = @user.items
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Save" %>
<% end %>

app/views/items/_item.html.erb
<tr id="item-<%= item.id %>">
  <td><h4><%= item.name %><h4></td>
  <td><center><%= item.days_left %></center></td>  
  <td><center><%= link_to "", user_item_path(item.user_id, item.id), method: :delete, remote: true , class: 'glyphicon glyphicon-ok' %></center></td>
</tr>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).hide();
<% else %>
  $('#item-' +<%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/items/new.html.erb
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <% if @user %>    
      <h1>Add New To-Do Item</h1>
      <%= render partial: 'form', locals: {user: @user, item: @item} %>
    <% else %>
      <h2>You must sign in to create To-Do items.</h2>
    <% end %>    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_home_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "To-Do Items", user_path(:id) %></li>
        <li><%= link_to "Add New To-Do Item", items_new_path %></li>
        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= link_to (current_user.name || current_user.email), user_path(:id) %>! 
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </u1>
    </div>
    
    <br/>
    <div class="container">
    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
      
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <br/>
        <h2 class="media-heading">User Profile</h2>
        <br/>
        <% if @user %>
          <h2 class="media-heading">name: <%= @user.name %></h2>
          <h2 class="media-heading">email: <%= @user.email %></h2>
          <% if @items.first %>
            <br/>
            <h2>To-Do Items</h2>
            <table class="table table-bordered table-condensed">
              <thead>
                <tr>
                  <th><h3>Item</h3></th>
                  <th><h3>Days Left</h3></th>
                  <th><h3>Complete</h3></th>
                </tr>
              </thead>
              <tbody>
                <% @items.each do |item| %>
                <%= render partial: 'items/item', locals: {user: @user, item: item} %>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <br/>
            <h2>No to-do items</h2>
          <% end %>
        <% else %>
          <br/>
          <h2>No user signed in</h2>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<br/>
<div class = "container">
  <div class="jumbotron">
    <h1>About Blocitoff</h1>
    <h3>Created by: steve lott, with direction from Bloc.io</h3>
  </div>
</div>

app/views/welcome/home.html.erb
<br/>
<div class = "container">
  <div class="jumbotron">
    <h1>Blocitoff</h1>
    <h3>Blocitoff is a To-Do list application</h3>
    <h3>that solves list clutter by automatically deleting out of date items.</h3>
  </div>
</div>